template: |
  ## 更新日志

  - 🧩 功能：语言列表支持拖动排序
  - 🧩 功能：新增「剑桥词典」查词
  - 🎨 设计：启用新的 logo
  - 🎨 设计：启用新的应用名 Lex
  - 🎨 设计：使用更纱黑体 UI SC 作为默认字体
  - 🪩 重构：翻译页面
  - ✨ 优化：字体设置移入应用设置
  - ✨ 优化：代理设置移动到应用设置
  - ✨ 优化：使用系统通知代替 SnackBar
  - ✨ 优化：语言设置页面优化
  - 🐞 修复：deb 包依赖缺失
