name: lex
description: 质感翻译
publish_to: "none"

version: 1.0.0+9

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  clipboard_watcher: ^0.2.0
  crypto: ^3.0.3
  dio: ^5.3.2
  dynamic_color: ^1.6.7
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hotkey_manager: ^0.2.0
  html: ^0.15.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  launch_at_startup: ^0.3.0
  local_notifier: ^0.1.5
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  process_run: ^0.14.0+1
  provider: ^6.0.5
  screen_retriever: ^0.1.9
  screen_text_extractor: ^0.1.3
  shared_preferences: ^2.2.1
  tray_manager: ^0.2.0
  url_launcher: ^6.1.14
  uuid: ^4.4.0
  window_manager: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo.ico
    - assets/service/translation/
    - assets/service/ocr/
