name: metranslate
description: 质感翻译
publish_to: "none"

version: 0.1.3+8

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  bitsdojo_window: ^0.1.5
  # bitsdojo_window 没有在 lib/ 中使用
  # 在 linux/my_application.cc 中使用
  # 作用是使窗口圆角处保持透明 (window_manager 无法实现)
  # 以及调整窗口大小 (window_manager DragToResizeArea 可实现)
  crypto: ^3.0.3
  dio: ^5.3.2
  dynamic_color: ^1.6.7
  file_picker: ^5.2.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hotkey_manager: ^0.1.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  launch_at_startup: ^0.2.2
  package_info_plus: ^3.1.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  screen_retriever: ^0.1.9
  screen_text_extractor: ^0.1.3
  shared_preferences: ^2.2.1
  tray_manager: ^0.2.0
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  window_manager: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo.ico
    - assets/service/
